### PR TITLE
fix(src/layout): ensure code blocks always scrollable

### LINKED ISSUE #52: code is not horizontally scrollable on mobile
I noticed that the code examples aren't horizontally scrollable on mobile (iOS) at all in some places (like here core/customization.md) or they could be improved with `-webkit-overflow-scrolling: touch` (like here (components/view-templates.md).

### PR DESCRIPTION
**Pull request by emcarru**
- move code block and copy link outside of code element, too

resolves #52

### CODE REVIEW

File: src/scripts/app.js [hunk 1]
```diff
@@ -52,21 +52,22 @@ function documentReady() {
...
     hljs.highlightBlock(block);
 
-    $(this).append('<button class="copy-button" data-clipboard-text="'+codeText+'"><p class="copy"><i class="fa fa-lg fa-paperclip" aria-hidden="true"></i>&nbsp;&nbsp;Copy</p><p class="copied"><i class="fa fa-lg fa-check" aria-hidden="true"></i>&nbsp;&nbsp;Copied to clipboard</p></button>');
+    $(this).parent().append('<button class="copy-button" data-clipboard-text="'+codeText+'"><p class="copy"><i class="fa fa-lg fa-paperclip" aria-hidden="true"></i>&nbsp;&nbsp;Copy</p><p class="copied"><i class="fa fa-lg fa-check" aria-hidden="true"></i>&nbsp;&nbsp;Copied to clipboard</p></button>');
     var heightOfCodeblock = $(this).height();
     if (heightOfCodeblock > 325) {
       $(this).height(365);
-      $(this).css('overflow', 'hidden');
-      $(this).append('<button class="expand-code-block-button"><p>Read more</p></button>');
+      $(this).css('overflow-y', 'hidden');
```
Comment (Qakulukiam) [inline src/scripts/app.js]: Does this mean non-expanded code blocks are scrollable? Should they be?

Comment (emcarru) [inline src/scripts/app.js]: only horizontally
